version: '3.8'

services:
  app:
    image: serversideup/php
    container_name: slimphp_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: php -S 0.0.0.0:8080 -t public
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: tasks_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret

  db:
    image: postgres:15
    container_name: slimphp_db
    restart: always
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
